# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
swift_version= '4.0'

target 'SearchByImage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchByImage
  pod "BWWalkthrough"

end
